name: JAAD
description:  JAAD transforms your markdown files into organized documentation with automatic navigation, table of contents, and a clean reading experience.
author: Luca Pattocchio <Kasui92>