import type { UiCatalog } from "../ui.ts";

export const ITALIAN_UI = {
  "breadcrumb.label": "Percorso di navigazione",
  "breadcrumb.root": "Documentazione",
  home: "Pagina iniziale",
  "locale.change": "Cambia lingua",
  "nav.documentation": "Navigazione della documentazione",
  "nav.jumpToSection": "Vai alla sezione...",
  "nav.mobile": "Apri o chiudi il menu mobile",
  "nav.page": "Navigazione tra le pagine",
  "nav.selectPage": "Seleziona pagina",
  "page.copied": "Copiata!",
  "page.copy": "Copia pagina",
  "page.edit": "Modifica questa pagina",
  "page.lastUpdated": "Ultimo aggiornamento il",
  scrollTop: "Torna in cima",
  "search.close": "chiudi",
  "search.empty": "Nessun risultato per",
  "search.label": "Cerca nella documentazione",
  "search.loading": "Caricamento...",
  "search.navigate": "naviga",
  "search.open": "apri",
  "search.placeholder": "Cerca nella documentazione...",
  "search.results": "Risultati della ricerca",
  "search.trigger": "Cerca nella documentazione...",
  "theme.toggle": "Cambia tema colore",
  "toc.label": "Indice dei contenuti",
  "toc.title": "In questa pagina",
} satisfies UiCatalog;
